"""TypedDict state contracts for the YiAlpha LangGraph pipeline.

Reducer semantics — IMPORTANT
-----------------------------
Every field below uses LangGraph's default **last-write-wins** merge: the
``Annotated[T, "..."]`` second argument is a human docstring, NOT a reducer
function. This is safe because the graph is *effectively serial per field* —
each field is written by exactly one node per run, so there is never a
conflicting concurrent write to reconcile.

The one exception is ``messages``, which inherits ``MessagesState``'s additive
reducer (append + ``RemoveMessage`` support) so the tool-loop clear-node can
both add and remove entries.

The two debate sub-states (``investment_debate_state``, ``risk_debate_state``)
are *replaced wholesale* by each speaker's return dict. Correctness therefore
depends on every speaker carrying forward all prior fields. Two helpers make
this carry-forward centralized and drift-proof:

* :func:`~yialpha.agents.utils.agent_utils.build_investment_debate_update`
  — bull/bear researchers.
* :func:`~yialpha.agents.utils.agent_utils.build_risk_debate_update`
  — aggressive/conservative/neutral debators.

These helpers are the compensating layer for the absence of field-level
reducers: they guarantee the full dict is rebuilt consistently on every turn,
so a speaker that forgets a field is a compile-time-style test failure
(``test_investment_debate_state.py`` / ``test_risk_debate_state.py``), not a
silent state drop.

Field ownership map (writer → field):
  START (propagation.create_initial_state) → all fields seeded
  Analysts    → market_report, sentiment_report, news_report, fundamentals_report
  Researchers → investment_debate_state (via build_investment_debate_update)
  Research Mgr→ investment_plan
  Trader      → trader_investment_plan, messages (AIMessage)
  Risk debators→ risk_debate_state (via build_risk_debate_update)
  Portfolio Mgr→ final_trade_decision, pm_rating, pm_decision_fields, risk_debate_state.judge_decision
"""

from typing import Annotated, Any

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    # V2.3 positioning split (flag-gated; key exists only on runs whose graph
    # carried the positioning analyst). Not read downstream yet — V2.4's
    # portfolio control consumes it.
    positioning_report: Annotated[str, "Report from the Positioning Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    pm_rating: Annotated[
        str,
        "The PM's structured rating (Buy/Overweight/Hold/Underweight/Sell) extracted"
        " directly from the PortfolioDecision, bypassing markdown parsing so the risk"
        " overlay never depends on text ordering. Empty string when the PM fell back to"
        " free-text (the overlay then falls back to parse_rating).",
    ]
    pm_decision_fields: Annotated[
        Any,
        "V2.0: the PM's PortfolioDecision fields the deterministic layers consume"
        " (price_target/confidence/probabilities/expected_return/invalidation/"
        "evidence_coverage + schema_version), as a plain dict. Empty dict on a"
        " free-text fallback — the ExecutionTicket builder treats missing fields as"
        " not-evaluated rather than guessing.",
    ]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    portfolio_state: Annotated[Any, "Optional live portfolio snapshot (Phase 1) for the Portfolio Manager"]
